export const fakeData = {
  "location": {
      "name": "New Delhi",
      "region": "Delhi",
      "country": "India",
      "lat": 28.6,
      "lon": 77.2,
      "tz_id": "Asia/Kolkata",
      "localtime_epoch": 1690023141,
      "localtime": "2023-07-22 16:22"
  },
  "current": {
      "last_updated_epoch": 1690022700,
      "last_updated": "2023-07-22 16:15",
      "temp_c": 35.0,
      "temp_f": 95.0,
      "is_day": 1,
      "condition": {
          "text": "Thundery outbreaks possible",
          "icon": "//cdn.weatherapi.com/weather/64x64/day/200.png",
          "code": 1087
      },
      "wind_mph": 9.4,
      "wind_kph": 15.1,
      "wind_degree": 80,
      "wind_dir": "E",
      "pressure_mb": 1004.0,
      "pressure_in": 29.65,
      "precip_mm": 0.0,
      "precip_in": 0.0,
      "humidity": 63,
      "cloud": 50,
      "feelslike_c": 35.5,
      "feelslike_f": 95.9,
      "vis_km": 4.0,
      "vis_miles": 2.0,
      "uv": 10.0,
      "gust_mph": 12.3,
      "gust_kph": 19.8,
      "air_quality": {
          "co": 774.4000244140625,
          "no2": 39.099998474121094,
          "o3": 65.0999984741211,
          "so2": 48.20000076293945,
          "pm2_5": 26.0,
          "pm10": 32.400001525878906,
          "us-epa-index": 2,
          "gb-defra-index": 3
      }
  },
  "forecast": {
      "forecastday": [
          {
              "date": "2023-07-22",
              "date_epoch": 1689984000,
              "day": {
                  "maxtemp_c": 40.3,
                  "maxtemp_f": 104.5,
                  "mintemp_c": 32.5,
                  "mintemp_f": 90.5,
                  "avgtemp_c": 36.2,
                  "avgtemp_f": 97.2,
                  "maxwind_mph": 13.2,
                  "maxwind_kph": 21.2,
                  "totalprecip_mm": 0.0,
                  "totalprecip_in": 0.0,
                  "totalsnow_cm": 0.0,
                  "avgvis_km": 10.0,
                  "avgvis_miles": 6.0,
                  "avghumidity": 43.0,
                  "daily_will_it_rain": 0,
                  "daily_chance_of_rain": 0,
                  "daily_will_it_snow": 0,
                  "daily_chance_of_snow": 0,
                  "condition": {
                      "text": "Sunny",
                      "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                      "code": 1000
                  },
                  "uv": 9.0,
                  "air_quality": {
                      "co": 881.2041702270508,
                      "no2": 42.13749980926514,
                      "o3": 32.17083336909612,
                      "so2": 49.54166634877523,
                      "pm2_5": 38.0708335240682,
                      "pm10": 49.36249987284342,
                      "us-epa-index": 2,
                      "gb-defra-index": 4
                  }
              },
              "astro": {
                  "sunrise": "05:37 AM",
                  "sunset": "07:18 PM",
                  "moonrise": "09:23 AM",
                  "moonset": "10:12 PM",
                  "moon_phase": "Waxing Crescent",
                  "moon_illumination": "15",
                  "is_moon_up": 0,
                  "is_sun_up": 0
              },
              "hour": [
                  {
                      "time_epoch": 1689964200,
                      "time": "2023-07-22 00:00",
                      "temp_c": 35.9,
                      "temp_f": 96.6,
                      "is_day": 0,
                      "condition": {
                          "text": "Partly cloudy",
                          "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                          "code": 1003
                      },
                      "wind_mph": 9.2,
                      "wind_kph": 14.8,
                      "wind_degree": 94,
                      "wind_dir": "E",
                      "pressure_mb": 1001.0,
                      "pressure_in": 29.54,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 43,
                      "cloud": 25,
                      "feelslike_c": 40.8,
                      "feelslike_f": 105.4,
                      "windchill_c": 35.9,
                      "windchill_f": 96.6,
                      "heatindex_c": 40.8,
                      "heatindex_f": 105.4,
                      "dewpoint_c": 21.4,
                      "dewpoint_f": 70.5,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 12.8,
                      "gust_kph": 20.5,
                      "uv": 1.0,
                      "air_quality": {
                          "co": 1642.199951171875,
                          "no2": 60.29999923706055,
                          "o3": 12.5,
                          "so2": 25.0,
                          "pm2_5": 85.0999984741211,
                          "pm10": 110.30000305175781,
                          "us-epa-index": 4,
                          "gb-defra-index": 10
                      }
                  },
                  {
                      "time_epoch": 1689967800,
                      "time": "2023-07-22 01:00",
                      "temp_c": 35.6,
                      "temp_f": 96.1,
                      "is_day": 0,
                      "condition": {
                          "text": "Clear",
                          "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                          "code": 1000
                      },
                      "wind_mph": 8.3,
                      "wind_kph": 13.3,
                      "wind_degree": 104,
                      "wind_dir": "ESE",
                      "pressure_mb": 1000.0,
                      "pressure_in": 29.54,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 45,
                      "cloud": 24,
                      "feelslike_c": 40.8,
                      "feelslike_f": 105.4,
                      "windchill_c": 35.6,
                      "windchill_f": 96.1,
                      "heatindex_c": 40.8,
                      "heatindex_f": 105.4,
                      "dewpoint_c": 21.8,
                      "dewpoint_f": 71.2,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 11.4,
                      "gust_kph": 18.4,
                      "uv": 1.0,
                      "air_quality": {
                          "co": 1228.300048828125,
                          "no2": 40.79999923706055,
                          "o3": 27.899999618530273,
                          "so2": 21.200000762939453,
                          "pm2_5": 72.80000305175781,
                          "pm10": 90.5999984741211,
                          "us-epa-index": 4,
                          "gb-defra-index": 10
                      }
                  },
                  {
                      "time_epoch": 1689971400,
                      "time": "2023-07-22 02:00",
                      "temp_c": 34.0,
                      "temp_f": 93.2,
                      "is_day": 0,
                      "condition": {
                          "text": "Partly cloudy",
                          "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                          "code": 1003
                      },
                      "wind_mph": 10.7,
                      "wind_kph": 17.3,
                      "wind_degree": 113,
                      "wind_dir": "ESE",
                      "pressure_mb": 1003.0,
                      "pressure_in": 29.61,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 50,
                      "cloud": 45,
                      "feelslike_c": 38.9,
                      "feelslike_f": 102.0,
                      "windchill_c": 34.0,
                      "windchill_f": 93.2,
                      "heatindex_c": 38.9,
                      "heatindex_f": 102.0,
                      "dewpoint_c": 22.1,
                      "dewpoint_f": 71.8,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 14.1,
                      "gust_kph": 22.7,
                      "uv": 1.0,
                      "air_quality": {
                          "co": 1014.7000122070312,
                          "no2": 30.5,
                          "o3": 37.599998474121094,
                          "so2": 21.700000762939453,
                          "pm2_5": 70.0999984741211,
                          "pm10": 84.5999984741211,
                          "us-epa-index": 4,
                          "gb-defra-index": 9
                      }
                  },
                  {
                      "time_epoch": 1689975000,
                      "time": "2023-07-22 03:00",
                      "temp_c": 33.4,
                      "temp_f": 92.1,
                      "is_day": 0,
                      "condition": {
                          "text": "Partly cloudy",
                          "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                          "code": 1003
                      },
                      "wind_mph": 10.7,
                      "wind_kph": 17.3,
                      "wind_degree": 109,
                      "wind_dir": "ESE",
                      "pressure_mb": 1003.0,
                      "pressure_in": 29.62,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 52,
                      "cloud": 28,
                      "feelslike_c": 38.2,
                      "feelslike_f": 100.8,
                      "windchill_c": 33.4,
                      "windchill_f": 92.1,
                      "heatindex_c": 38.2,
                      "heatindex_f": 100.8,
                      "dewpoint_c": 22.2,
                      "dewpoint_f": 72.0,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 14.1,
                      "gust_kph": 22.7,
                      "uv": 1.0,
                      "air_quality": {
                          "co": 907.9000244140625,
                          "no2": 27.100000381469727,
                          "o3": 40.099998474121094,
                          "so2": 24.600000381469727,
                          "pm2_5": 71.80000305175781,
                          "pm10": 83.4000015258789,
                          "us-epa-index": 4,
                          "gb-defra-index": 10
                      }
                  },
                  {
                      "time_epoch": 1689978600,
                      "time": "2023-07-22 04:00",
                      "temp_c": 32.9,
                      "temp_f": 91.2,
                      "is_day": 0,
                      "condition": {
                          "text": "Clear",
                          "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                          "code": 1000
                      },
                      "wind_mph": 10.7,
                      "wind_kph": 17.3,
                      "wind_degree": 105,
                      "wind_dir": "ESE",
                      "pressure_mb": 1003.0,
                      "pressure_in": 29.62,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 54,
                      "cloud": 19,
                      "feelslike_c": 37.6,
                      "feelslike_f": 99.7,
                      "windchill_c": 32.9,
                      "windchill_f": 91.2,
                      "heatindex_c": 37.6,
                      "heatindex_f": 99.7,
                      "dewpoint_c": 22.2,
                      "dewpoint_f": 72.0,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 14.1,
                      "gust_kph": 22.7,
                      "uv": 1.0,
                      "air_quality": {
                          "co": 867.7999877929688,
                          "no2": 26.700000762939453,
                          "o3": 35.79999923706055,
                          "so2": 28.100000381469727,
                          "pm2_5": 73.69999694824219,
                          "pm10": 82.30000305175781,
                          "us-epa-index": 4,
                          "gb-defra-index": 10
                      }
                  },
                  {
                      "time_epoch": 1689982200,
                      "time": "2023-07-22 05:00",
                      "temp_c": 32.5,
                      "temp_f": 90.5,
                      "is_day": 0,
                      "condition": {
                          "text": "Clear",
                          "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                          "code": 1000
                      },
                      "wind_mph": 10.7,
                      "wind_kph": 17.3,
                      "wind_degree": 109,
                      "wind_dir": "ESE",
                      "pressure_mb": 1003.0,
                      "pressure_in": 29.63,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 54,
                      "cloud": 18,
                      "feelslike_c": 36.9,
                      "feelslike_f": 98.4,
                      "windchill_c": 32.5,
                      "windchill_f": 90.5,
                      "heatindex_c": 36.9,
                      "heatindex_f": 98.4,
                      "dewpoint_c": 22.0,
                      "dewpoint_f": 71.6,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 14.3,
                      "gust_kph": 23.0,
                      "uv": 1.0,
                      "air_quality": {
                          "co": 834.5,
                          "no2": 28.100000381469727,
                          "o3": 31.5,
                          "so2": 34.29999923706055,
                          "pm2_5": 72.9000015258789,
                          "pm10": 79.0,
                          "us-epa-index": 4,
                          "gb-defra-index": 10
                      }
                  },
                  {
                      "time_epoch": 1689985800,
                      "time": "2023-07-22 06:00",
                      "temp_c": 32.5,
                      "temp_f": 90.5,
                      "is_day": 1,
                      "condition": {
                          "text": "Sunny",
                          "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                          "code": 1000
                      },
                      "wind_mph": 10.5,
                      "wind_kph": 16.9,
                      "wind_degree": 108,
                      "wind_dir": "ESE",
                      "pressure_mb": 1004.0,
                      "pressure_in": 29.65,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 54,
                      "cloud": 19,
                      "feelslike_c": 36.9,
                      "feelslike_f": 98.4,
                      "windchill_c": 32.5,
                      "windchill_f": 90.5,
                      "heatindex_c": 36.9,
                      "heatindex_f": 98.4,
                      "dewpoint_c": 22.1,
                      "dewpoint_f": 71.8,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 13.6,
                      "gust_kph": 22.0,
                      "uv": 8.0,
                      "air_quality": {
                          "co": 794.4000244140625,
                          "no2": 31.899999618530273,
                          "o3": 24.299999237060547,
                          "so2": 43.400001525878906,
                          "pm2_5": 70.9000015258789,
                          "pm10": 75.9000015258789,
                          "us-epa-index": 4,
                          "gb-defra-index": 9
                      }
                  },
                  {
                      "time_epoch": 1689989400,
                      "time": "2023-07-22 07:00",
                      "temp_c": 33.0,
                      "temp_f": 91.4,
                      "is_day": 1,
                      "condition": {
                          "text": "Sunny",
                          "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                          "code": 1000
                      },
                      "wind_mph": 12.3,
                      "wind_kph": 19.8,
                      "wind_degree": 108,
                      "wind_dir": "ESE",
                      "pressure_mb": 1004.0,
                      "pressure_in": 29.66,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 53,
                      "cloud": 16,
                      "feelslike_c": 37.5,
                      "feelslike_f": 99.5,
                      "windchill_c": 33.0,
                      "windchill_f": 91.4,
                      "heatindex_c": 37.5,
                      "heatindex_f": 99.5,
                      "dewpoint_c": 22.1,
                      "dewpoint_f": 71.8,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 14.1,
                      "gust_kph": 22.7,
                      "uv": 8.0,
                      "air_quality": {
                          "co": 881.2000122070312,
                          "no2": 41.099998474121094,
                          "o3": 12.199999809265137,
                          "so2": 50.599998474121094,
                          "pm2_5": 68.19999694824219,
                          "pm10": 74.69999694824219,
                          "us-epa-index": 4,
                          "gb-defra-index": 9
                      }
                  },
                  {
                      "time_epoch": 1689993000,
                      "time": "2023-07-22 08:00",
                      "temp_c": 33.9,
                      "temp_f": 93.0,
                      "is_day": 1,
                      "condition": {
                          "text": "Sunny",
                          "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                          "code": 1000
                      },
                      "wind_mph": 13.0,
                      "wind_kph": 20.9,
                      "wind_degree": 112,
                      "wind_dir": "ESE",
                      "pressure_mb": 1005.0,
                      "pressure_in": 29.67,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 51,
                      "cloud": 13,
                      "feelslike_c": 38.9,
                      "feelslike_f": 102.0,
                      "windchill_c": 33.9,
                      "windchill_f": 93.0,
                      "heatindex_c": 38.9,
                      "heatindex_f": 102.0,
                      "dewpoint_c": 22.2,
                      "dewpoint_f": 72.0,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 15.0,
                      "gust_kph": 24.1,
                      "uv": 8.0,
                      "air_quality": {
                          "co": 961.2999877929688,
                          "no2": 48.70000076293945,
                          "o3": 7.0,
                          "so2": 57.20000076293945,
                          "pm2_5": 61.099998474121094,
                          "pm10": 68.80000305175781,
                          "us-epa-index": 3,
                          "gb-defra-index": 8
                      }
                  },
                  {
                      "time_epoch": 1689996600,
                      "time": "2023-07-22 09:00",
                      "temp_c": 35.0,
                      "temp_f": 95.0,
                      "is_day": 1,
                      "condition": {
                          "text": "Sunny",
                          "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                          "code": 1000
                      },
                      "wind_mph": 12.5,
                      "wind_kph": 20.2,
                      "wind_degree": 116,
                      "wind_dir": "ESE",
                      "pressure_mb": 1005.0,
                      "pressure_in": 29.67,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 48,
                      "cloud": 13,
                      "feelslike_c": 40.5,
                      "feelslike_f": 104.9,
                      "windchill_c": 35.0,
                      "windchill_f": 95.0,
                      "heatindex_c": 40.5,
                      "heatindex_f": 104.9,
                      "dewpoint_c": 22.3,
                      "dewpoint_f": 72.1,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 14.3,
                      "gust_kph": 23.0,
                      "uv": 9.0,
                      "air_quality": {
                          "co": 921.2999877929688,
                          "no2": 47.29999923706055,
                          "o3": 14.5,
                          "so2": 62.0,
                          "pm2_5": 49.70000076293945,
                          "pm10": 58.099998474121094,
                          "us-epa-index": 3,
                          "gb-defra-index": 6
                      }
                  },
                  {
                      "time_epoch": 1690000200,
                      "time": "2023-07-22 10:00",
                      "temp_c": 36.2,
                      "temp_f": 97.2,
                      "is_day": 1,
                      "condition": {
                          "text": "Sunny",
                          "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                          "code": 1000
                      },
                      "wind_mph": 12.3,
                      "wind_kph": 19.8,
                      "wind_degree": 121,
                      "wind_dir": "ESE",
                      "pressure_mb": 1004.0,
                      "pressure_in": 29.66,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 44,
                      "cloud": 11,
                      "feelslike_c": 41.9,
                      "feelslike_f": 107.4,
                      "windchill_c": 36.2,
                      "windchill_f": 97.2,
                      "heatindex_c": 41.9,
                      "heatindex_f": 107.4,
                      "dewpoint_c": 22.2,
                      "dewpoint_f": 72.0,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 14.1,
                      "gust_kph": 22.7,
                      "uv": 9.0,
                      "air_quality": {
                          "co": 854.5,
                          "no2": 44.599998474121094,
                          "o3": 18.100000381469727,
                          "so2": 61.0,
                          "pm2_5": 45.599998474121094,
                          "pm10": 54.5,
                          "us-epa-index": 3,
                          "gb-defra-index": 5
                      }
                  },
                  {
                      "time_epoch": 1690003800,
                      "time": "2023-07-22 11:00",
                      "temp_c": 38.4,
                      "temp_f": 101.1,
                      "is_day": 1,
                      "condition": {
                          "text": "Sunny",
                          "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                          "code": 1000
                      },
                      "wind_mph": 11.9,
                      "wind_kph": 19.1,
                      "wind_degree": 121,
                      "wind_dir": "ESE",
                      "pressure_mb": 1004.0,
                      "pressure_in": 29.65,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 41,
                      "cloud": 18,
                      "feelslike_c": 45.5,
                      "feelslike_f": 113.9,
                      "windchill_c": 38.4,
                      "windchill_f": 101.1,
                      "heatindex_c": 45.5,
                      "heatindex_f": 113.9,
                      "dewpoint_c": 22.8,
                      "dewpoint_f": 73.0,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 13.6,
                      "gust_kph": 22.0,
                      "uv": 9.0,
                      "air_quality": {
                          "co": 807.7999877929688,
                          "no2": 39.099998474121094,
                          "o3": 24.700000762939453,
                          "so2": 54.400001525878906,
                          "pm2_5": 42.70000076293945,
                          "pm10": 50.5,
                          "us-epa-index": 3,
                          "gb-defra-index": 5
                      }
                  },
                  {
                      "time_epoch": 1690007400,
                      "time": "2023-07-22 12:00",
                      "temp_c": 39.4,
                      "temp_f": 102.9,
                      "is_day": 1,
                      "condition": {
                          "text": "Sunny",
                          "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                          "code": 1000
                      },
                      "wind_mph": 11.0,
                      "wind_kph": 17.6,
                      "wind_degree": 116,
                      "wind_dir": "ESE",
                      "pressure_mb": 1003.0,
                      "pressure_in": 29.63,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 37,
                      "cloud": 24,
                      "feelslike_c": 45.9,
                      "feelslike_f": 114.6,
                      "windchill_c": 39.4,
                      "windchill_f": 102.9,
                      "heatindex_c": 45.9,
                      "heatindex_f": 114.6,
                      "dewpoint_c": 21.9,
                      "dewpoint_f": 71.4,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 12.5,
                      "gust_kph": 20.2,
                      "uv": 9.0,
                      "air_quality": {
                          "co": 727.7000122070312,
                          "no2": 30.899999618530273,
                          "o3": 50.099998474121094,
                          "so2": 39.599998474121094,
                          "pm2_5": 32.099998474121094,
                          "pm10": 37.099998474121094,
                          "us-epa-index": 2,
                          "gb-defra-index": 3
                      }
                  },
                  {
                      "time_epoch": 1690011000,
                      "time": "2023-07-22 13:00",
                      "temp_c": 40.0,
                      "temp_f": 104.0,
                      "is_day": 1,
                      "condition": {
                          "text": "Partly cloudy",
                          "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                          "code": 1003
                      },
                      "wind_mph": 11.0,
                      "wind_kph": 17.6,
                      "wind_degree": 103,
                      "wind_dir": "ESE",
                      "pressure_mb": 1003.0,
                      "pressure_in": 29.61,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 33,
                      "cloud": 31,
                      "feelslike_c": 45.5,
                      "feelslike_f": 113.9,
                      "windchill_c": 40.0,
                      "windchill_f": 104.0,
                      "heatindex_c": 45.5,
                      "heatindex_f": 113.9,
                      "dewpoint_c": 20.9,
                      "dewpoint_f": 69.6,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 12.5,
                      "gust_kph": 20.2,
                      "uv": 10.0,
                      "air_quality": {
                          "co": 694.2999877929688,
                          "no2": 26.700000762939453,
                          "o3": 69.4000015258789,
                          "so2": 32.0,
                          "pm2_5": 24.0,
                          "pm10": 28.100000381469727,
                          "us-epa-index": 2,
                          "gb-defra-index": 3
                      }
                  },
                  {
                      "time_epoch": 1690014600,
                      "time": "2023-07-22 14:00",
                      "temp_c": 40.2,
                      "temp_f": 104.4,
                      "is_day": 1,
                      "condition": {
                          "text": "Partly cloudy",
                          "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                          "code": 1003
                      },
                      "wind_mph": 12.3,
                      "wind_kph": 19.8,
                      "wind_degree": 92,
                      "wind_dir": "E",
                      "pressure_mb": 1002.0,
                      "pressure_in": 29.59,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 31,
                      "cloud": 46,
                      "feelslike_c": 45.0,
                      "feelslike_f": 113.0,
                      "windchill_c": 40.2,
                      "windchill_f": 104.4,
                      "heatindex_c": 45.0,
                      "heatindex_f": 113.0,
                      "dewpoint_c": 20.0,
                      "dewpoint_f": 68.0,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 14.1,
                      "gust_kph": 22.7,
                      "uv": 10.0,
                      "air_quality": {
                          "co": 687.5999755859375,
                          "no2": 26.399999618530273,
                          "o3": 75.0999984741211,
                          "so2": 32.0,
                          "pm2_5": 20.600000381469727,
                          "pm10": 24.700000762939453,
                          "us-epa-index": 2,
                          "gb-defra-index": 2
                      }
                  },
                  {
                      "time_epoch": 1690018200,
                      "time": "2023-07-22 15:00",
                      "temp_c": 40.3,
                      "temp_f": 104.5,
                      "is_day": 1,
                      "condition": {
                          "text": "Partly cloudy",
                          "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                          "code": 1003
                      },
                      "wind_mph": 11.4,
                      "wind_kph": 18.4,
                      "wind_degree": 89,
                      "wind_dir": "E",
                      "pressure_mb": 1001.0,
                      "pressure_in": 29.57,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 30,
                      "cloud": 46,
                      "feelslike_c": 44.4,
                      "feelslike_f": 111.9,
                      "windchill_c": 40.3,
                      "windchill_f": 104.5,
                      "heatindex_c": 44.4,
                      "heatindex_f": 111.9,
                      "dewpoint_c": 19.2,
                      "dewpoint_f": 66.6,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 13.2,
                      "gust_kph": 21.2,
                      "uv": 10.0,
                      "air_quality": {
                          "co": 701.0,
                          "no2": 28.5,
                          "o3": 75.80000305175781,
                          "so2": 35.29999923706055,
                          "pm2_5": 21.0,
                          "pm10": 25.899999618530273,
                          "us-epa-index": 2,
                          "gb-defra-index": 2
                      }
                  },
                  {
                      "time_epoch": 1690021800,
                      "time": "2023-07-22 16:00",
                      "temp_c": 40.0,
                      "temp_f": 104.0,
                      "is_day": 1,
                      "condition": {
                          "text": "Partly cloudy",
                          "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                          "code": 1003
                      },
                      "wind_mph": 10.7,
                      "wind_kph": 17.3,
                      "wind_degree": 90,
                      "wind_dir": "E",
                      "pressure_mb": 1001.0,
                      "pressure_in": 29.55,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 31,
                      "cloud": 44,
                      "feelslike_c": 44.3,
                      "feelslike_f": 111.7,
                      "windchill_c": 40.0,
                      "windchill_f": 104.0,
                      "heatindex_c": 44.3,
                      "heatindex_f": 111.7,
                      "dewpoint_c": 19.5,
                      "dewpoint_f": 67.1,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 12.3,
                      "gust_kph": 19.8,
                      "uv": 10.0,
                      "air_quality": {
                          "co": 774.4000244140625,
                          "no2": 39.099998474121094,
                          "o3": 65.0999984741211,
                          "so2": 48.20000076293945,
                          "pm2_5": 26.0,
                          "pm10": 32.400001525878906,
                          "us-epa-index": 2,
                          "gb-defra-index": 3
                      }
                  },
                  {
                      "time_epoch": 1690025400,
                      "time": "2023-07-22 17:00",
                      "temp_c": 38.8,
                      "temp_f": 101.8,
                      "is_day": 1,
                      "condition": {
                          "text": "Partly cloudy",
                          "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                          "code": 1003
                      },
                      "wind_mph": 13.2,
                      "wind_kph": 21.2,
                      "wind_degree": 90,
                      "wind_dir": "E",
                      "pressure_mb": 1001.0,
                      "pressure_in": 29.55,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 35,
                      "cloud": 25,
                      "feelslike_c": 43.9,
                      "feelslike_f": 111.0,
                      "windchill_c": 38.8,
                      "windchill_f": 101.8,
                      "heatindex_c": 43.9,
                      "heatindex_f": 111.0,
                      "dewpoint_c": 20.8,
                      "dewpoint_f": 69.4,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 15.2,
                      "gust_kph": 24.5,
                      "uv": 9.0,
                      "air_quality": {
                          "co": 881.2000122070312,
                          "no2": 61.0,
                          "o3": 42.900001525878906,
                          "so2": 79.19999694824219,
                          "pm2_5": 35.099998474121094,
                          "pm10": 43.099998474121094,
                          "us-epa-index": 2,
                          "gb-defra-index": 3
                      }
                  },
                  {
                      "time_epoch": 1690029000,
                      "time": "2023-07-22 18:00",
                      "temp_c": 37.2,
                      "temp_f": 99.0,
                      "is_day": 1,
                      "condition": {
                          "text": "Sunny",
                          "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                          "code": 1000
                      },
                      "wind_mph": 12.3,
                      "wind_kph": 19.8,
                      "wind_degree": 96,
                      "wind_dir": "E",
                      "pressure_mb": 1001.0,
                      "pressure_in": 29.56,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 40,
                      "cloud": 18,
                      "feelslike_c": 42.5,
                      "feelslike_f": 108.5,
                      "windchill_c": 37.2,
                      "windchill_f": 99.0,
                      "heatindex_c": 42.5,
                      "heatindex_f": 108.5,
                      "dewpoint_c": 21.4,
                      "dewpoint_f": 70.5,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 14.1,
                      "gust_kph": 22.7,
                      "uv": 9.0,
                      "air_quality": {
                          "co": 1094.800048828125,
                          "no2": 89.0999984741211,
                          "o3": 17.5,
                          "so2": 113.5,
                          "pm2_5": 50.099998474121094,
                          "pm10": 62.29999923706055,
                          "us-epa-index": 3,
                          "gb-defra-index": 6
                      }
                  },
                  {
                      "time_epoch": 1690032600,
                      "time": "2023-07-22 19:00",
                      "temp_c": 36.5,
                      "temp_f": 97.7,
                      "is_day": 0,
                      "condition": {
                          "text": "Partly cloudy",
                          "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                          "code": 1003
                      },
                      "wind_mph": 11.0,
                      "wind_kph": 17.6,
                      "wind_degree": 97,
                      "wind_dir": "E",
                      "pressure_mb": 1001.0,
                      "pressure_in": 29.56,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 41,
                      "cloud": 26,
                      "feelslike_c": 41.4,
                      "feelslike_f": 106.5,
                      "windchill_c": 36.5,
                      "windchill_f": 97.7,
                      "heatindex_c": 41.4,
                      "heatindex_f": 106.5,
                      "dewpoint_c": 21.2,
                      "dewpoint_f": 70.2,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 13.9,
                      "gust_kph": 22.3,
                      "uv": 1.0,
                      "air_quality": {
                          "co": 1415.300048828125,
                          "no2": 97.30000305175781,
                          "o3": 4.5,
                          "so2": 110.5999984741211,
                          "pm2_5": 65.30000305175781,
                          "pm10": 85.0999984741211,
                          "us-epa-index": 3,
                          "gb-defra-index": 9
                      }
                  },
                  {
                      "time_epoch": 1690036200,
                      "time": "2023-07-22 20:00",
                      "temp_c": 36.3,
                      "temp_f": 97.3,
                      "is_day": 0,
                      "condition": {
                          "text": "Clear",
                          "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                          "code": 1000
                      },
                      "wind_mph": 9.6,
                      "wind_kph": 15.5,
                      "wind_degree": 92,
                      "wind_dir": "E",
                      "pressure_mb": 1002.0,
                      "pressure_in": 29.58,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 42,
                      "cloud": 13,
                      "feelslike_c": 41.1,
                      "feelslike_f": 106.0,
                      "windchill_c": 36.3,
                      "windchill_f": 97.3,
                      "heatindex_c": 41.1,
                      "heatindex_f": 106.0,
                      "dewpoint_c": 21.2,
                      "dewpoint_f": 70.2,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 12.5,
                      "gust_kph": 20.2,
                      "uv": 1.0,
                      "air_quality": {
                          "co": 1615.5,
                          "no2": 82.30000305175781,
                          "o3": 2.700000047683716,
                          "so2": 83.0,
                          "pm2_5": 73.0999984741211,
                          "pm10": 100.0999984741211,
                          "us-epa-index": 4,
                          "gb-defra-index": 10
                      }
                  },
                  {
                      "time_epoch": 1690039800,
                      "time": "2023-07-22 21:00",
                      "temp_c": 35.9,
                      "temp_f": 96.6,
                      "is_day": 0,
                      "condition": {
                          "text": "Partly cloudy",
                          "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                          "code": 1003
                      },
                      "wind_mph": 9.4,
                      "wind_kph": 15.1,
                      "wind_degree": 89,
                      "wind_dir": "E",
                      "pressure_mb": 1002.0,
                      "pressure_in": 29.6,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 43,
                      "cloud": 35,
                      "feelslike_c": 40.8,
                      "feelslike_f": 105.4,
                      "windchill_c": 35.9,
                      "windchill_f": 96.6,
                      "heatindex_c": 40.8,
                      "heatindex_f": 105.4,
                      "dewpoint_c": 21.4,
                      "dewpoint_f": 70.5,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 12.5,
                      "gust_kph": 20.2,
                      "uv": 1.0,
                      "air_quality": {
                          "co": 1668.9000244140625,
                          "no2": 67.19999694824219,
                          "o3": 3.0,
                          "so2": 63.900001525878906,
                          "pm2_5": 75.80000305175781,
                          "pm10": 106.80000305175781,
                          "us-epa-index": 4,
                          "gb-defra-index": 10
                      }
                  },
                  {
                      "time_epoch": 1690043400,
                      "time": "2023-07-22 22:00",
                      "temp_c": 35.5,
                      "temp_f": 95.9,
                      "is_day": 0,
                      "condition": {
                          "text": "Partly cloudy",
                          "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                          "code": 1003
                      },
                      "wind_mph": 10.7,
                      "wind_kph": 17.3,
                      "wind_degree": 92,
                      "wind_dir": "E",
                      "pressure_mb": 1003.0,
                      "pressure_in": 29.61,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 45,
                      "cloud": 46,
                      "feelslike_c": 40.5,
                      "feelslike_f": 104.9,
                      "windchill_c": 35.5,
                      "windchill_f": 95.9,
                      "heatindex_c": 40.5,
                      "heatindex_f": 104.9,
                      "dewpoint_c": 21.6,
                      "dewpoint_f": 70.9,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 14.3,
                      "gust_kph": 23.0,
                      "uv": 1.0,
                      "air_quality": {
                          "co": 1562.0999755859375,
                          "no2": 58.29999923706055,
                          "o3": 3.5999999046325684,
                          "so2": 56.29999923706055,
                          "pm2_5": 71.5999984741211,
                          "pm10": 101.4000015258789,
                          "us-epa-index": 4,
                          "gb-defra-index": 10
                      }
                  },
                  {
                      "time_epoch": 1690047000,
                      "time": "2023-07-22 23:00",
                      "temp_c": 35.3,
                      "temp_f": 95.5,
                      "is_day": 0,
                      "condition": {
                          "text": "Clear",
                          "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                          "code": 1000
                      },
                      "wind_mph": 12.5,
                      "wind_kph": 20.2,
                      "wind_degree": 122,
                      "wind_dir": "ESE",
                      "pressure_mb": 1003.0,
                      "pressure_in": 29.62,
                      "precip_mm": 0.0,
                      "precip_in": 0.0,
                      "humidity": 45,
                      "cloud": 17,
                      "feelslike_c": 40.2,
                      "feelslike_f": 104.4,
                      "windchill_c": 35.3,
                      "windchill_f": 95.5,
                      "heatindex_c": 40.2,
                      "heatindex_f": 104.4,
                      "dewpoint_c": 21.6,
                      "dewpoint_f": 70.9,
                      "will_it_rain": 0,
                      "chance_of_rain": 0,
                      "will_it_snow": 0,
                      "chance_of_snow": 0,
                      "vis_km": 10.0,
                      "vis_miles": 6.0,
                      "gust_mph": 15.7,
                      "gust_kph": 25.2,
                      "uv": 1.0,
                      "air_quality": {
                          "co": 1255.0,
                          "no2": 52.79999923706055,
                          "o3": 3.799999952316284,
                          "so2": 52.900001525878906,
                          "pm2_5": 55.900001525878906,
                          "pm10": 78.69999694824219,
                          "us-epa-index": 3,
                          "gb-defra-index": 7
                      }
                  }
              ]
          }
      ]
  },
  "alerts": {
      "alert": [
          
      ]
  }
}